### ISSUE TITLE
User Data Path truncation

### ISSUE THREAD

**Issue by mikeduglas** [david-risney/WebView2Utilities#30]
Host Apps tab: User Data Path is truncated after first spacebar. For example, my user data path "c:\Users\Mike Duglas\AppData\Roaming\MikeDuglas\" becomes "c:\Users\Mike".

**Comment by david-risney** [comment]
Yeah that's from the bad code I have for parsing the command line.  I should probably find a library to do that for me instead.

**Comment by david-risney** [comment]
Thanks for this bug report by the way!
