### ISSUE TITLE
Create reports without needing the host app running

### ISSUE THREAD

**Issue by david-risney** [david-risney/WebView2Utilities#69]
Often want to create reports for apps that are crashing with WebView2. WebView2Util can't cover cases where app crashes at launch if it can only create reports for running apps. Perhaps cache last user data folder. Or perhaps use ETW events to find app crashes.

**Comment by victorhuangwq** [comment]
- [ ] Add a checkbox that states "Display previously active apps" (By default checked)
- [ ] Show previously active apps. Display N/A for the PIDs.
- [ ] Up for discussion - State column

<img width="954" alt="image" src="https://github.com/david-risney/WebView2Utilities/assets/5773562/77b385ab-ae5b-4e7b-b3a3-7a3a4da2f0a8">

**Comment by david-risney** [comment]
* I think the checkbox is probably not necessary. We can just always show terminated host apps in the list. I'll remove the terminated entry when a corresponding running entry shows up.
* I'm calling it 'Status' and its currently either Running or Terminated. In the PID text box I'm adding the status text if its not Running.
* Seems like it will be good to give them a slightly gray color and to try to put them at the bottom.

**Comment by victorhuangwq** [comment]
> I'm calling it 'Status' and its currently either Running or Terminated. In the PID text box I'm adding the status text if its not Running.

This is a good idea

> Seems like it will be good to give them a slightly gray color and to try to put them at the bottom.

I do think the current blue for running, and then black or dark grey for terminated would work. a straight gray is a little tiring when it comes to contrast.

**Comment by david-risney** [comment]
I'll see if I can figure out a way for WPF to tell me some colors to use.

**Comment by david-risney** [comment]
There is an API for standard OS colors for different purposes so it will continue working when changing theme or high contrast mode or whatever. I'm using ControlText for the normal list view items I've and the 'GrayText' color for the terminated items which is intended for disabled items. The gray used here is darker than what I was using originally and I think looks nicer.
